import type { Metadata } from "next";
import "@repo/ui/styles/global.css";
import styles from './layout.module.css';

export const metadata: Metadata = {
  title: "Create Next App Template",
  description: "Generated by template",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ru">
      <body>
        <div className={styles.root_layout}>
          <div className={styles.root_content}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
